<?php

return [
    'arun' => [
        'name' => 'Arun',
        'slug' => 'arun',
        'headline' => 'Founder of TITORA',
        'bio' => 'Building TITORA, DOOB and digital infrastructure products.',
        'theme' => 'default',
        'avatar' => null,
        'avatar_alt' => 'Arun',
        'is_verified' => true,
        'seo_title' => null,
        'seo_description' => null,
        'links' => [
            [
                'id' => 'arun-website',
                'title' => 'Visit Website',
                'description' => null,
                'url' => 'https://titora.co.in',
                'type' => 'website',
                'is_featured' => true,
            ],
            [
                'id' => 'arun-instagram',
                'title' => 'Instagram',
                'description' => null,
                'url' => 'https://instagram.com',
                'type' => 'instagram',
                'is_featured' => false,
            ],
        ],
    ],
    'titora' => [
        'name' => 'TITORA',
        'slug' => 'titora',
        'headline' => 'Premium SaaS Platform',
        'bio' => null,
        'theme' => 'titora',
        'avatar' => null,
        'avatar_alt' => 'TITORA',
        'is_verified' => true,
        'seo_title' => null,
        'seo_description' => null,
        'links' => [
            [
                'id' => 'titora-website',
                'title' => 'Visit Website',
                'description' => null,
                'url' => 'https://titora.co.in',
                'type' => 'website',
                'is_featured' => true,
            ],
            [
                'id' => 'titora-instagram',
                'title' => 'Instagram',
                'description' => null,
                'url' => 'https://instagram.com',
                'type' => 'instagram',
                'is_featured' => false,
            ],
        ],
    ],
    'doob' => [
        'name' => 'DOOB',
        'slug' => 'doob',
        'headline' => 'DOOB Platform',
        'bio' => null,
        'theme' => 'doob',
        'avatar' => null,
        'avatar_alt' => 'DOOB',
        'is_verified' => true,
        'seo_title' => null,
        'seo_description' => null,
        'links' => [
            [
                'id' => 'doob-website',
                'title' => 'Visit Website',
                'description' => null,
                'url' => 'https://titora.co.in',
                'type' => 'website',
                'is_featured' => true,
            ],
        ],
    ],
    'karadavi' => [
        'name' => 'KARADAVI',
        'slug' => 'karadavi',
        'headline' => 'KARADAVI Brand',
        'bio' => null,
        'theme' => 'karadavi',
        'avatar' => null,
        'avatar_alt' => 'KARADAVI',
        'is_verified' => true,
        'seo_title' => null,
        'seo_description' => null,
        'links' => [
            [
                'id' => 'karadavi-website',
                'title' => 'Visit Website',
                'description' => null,
                'url' => 'https://titora.co.in',
                'type' => 'website',
                'is_featured' => true,
            ],
        ],
    ],
    'smxm' => [
        'name' => 'SMXM',
        'slug' => 'smxm',
        'headline' => 'SMXM Platform',
        'bio' => null,
        'theme' => 'smxm',
        'avatar' => null,
        'avatar_alt' => 'SMXM',
        'is_verified' => true,
        'seo_title' => null,
        'seo_description' => null,
        'links' => [
            [
                'id' => 'smxm-website',
                'title' => 'Visit Website',
                'description' => null,
                'url' => 'https://titora.co.in',
                'type' => 'website',
                'is_featured' => true,
            ],
        ],
    ],
    'links' => [
        'name' => 'TITORA Links',
        'slug' => 'links',
        'headline' => 'The Platform Itself',
        'bio' => null,
        'theme' => 'default',
        'avatar' => null,
        'avatar_alt' => 'TITORA Links',
        'is_verified' => true,
        'seo_title' => null,
        'seo_description' => null,
        'links' => [
            [
                'id' => 'links-website',
                'title' => 'Visit Website',
                'description' => null,
                'url' => 'https://titora.co.in',
                'type' => 'website',
                'is_featured' => true,
            ],
        ],
    ],
];
